package i5.las2peer.services.videoListService;


import java.net.HttpURLConnection;

import javax.ws.rs.DELETE;
import javax.ws.rs.GET;
import javax.ws.rs.POST;
import javax.ws.rs.PUT;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.Consumes;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.MediaType;

import com.fasterxml.jackson.core.JsonProcessingException;

import i5.las2peer.api.Service;
import i5.las2peer.api.Context;
import i5.las2peer.restMapper.RESTService;
import i5.las2peer.restMapper.annotations.ServicePath;
import i5.las2peer.services.videoListService.database.DatabaseManager;
import java.sql.*;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Contact;
import io.swagger.annotations.Info;
import io.swagger.annotations.License;
import io.swagger.annotations.SwaggerDefinition;
import org.json.simple.*;
 

/**
 *
 * VideoListService
 *
 * This microservice was generated by the CAE (Community Application Editor). If you edit it, please
 * make sure to keep the general structure of the file and only add the body of the methods provided
 * in this main file. Private methods are also allowed, but any "deeper" functionality should be
 * outsourced to (imported) classes.
 *
 */
@ServicePath("videos")
public class VideoListService extends RESTService {


  /*
   * Database configuration
   */
  private String jdbcDriverClassName;
  private String jdbcLogin;
  private String jdbcPass;
  private String jdbcUrl;
  private String jdbcSchema;
  private DatabaseManager dbm;



  public VideoListService() {
	super();
    // read and set properties values
    setFieldValues();
    // instantiate a database manager to handle database connection pooling and credentials
    dbm = new DatabaseManager(jdbcDriverClassName, jdbcLogin, jdbcPass, jdbcUrl, jdbcSchema);
  }

  @Override
  public void initResources() {
	getResourceConfig().register(RootResource.class);
  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // REST methods
  // //////////////////////////////////////////////////////////////////////////////////////

  @Api
  @SwaggerDefinition(
      info = @Info(title = "VideoListService", version = "1.0",
          description = "A las2peer microservice generated by the CAE.",
          termsOfService = "none",
          contact = @Contact(name = "Peter de Lange", email = "CAEAddress@gmail.com") ,
          license = @License(name = "BSD",
              url = "https://github.com/CAE-Community-Application-Editor/microservice-VideoListService/blob/master/LICENSE.txt") ) )
  @Path("/")
  public static class RootResource {

    private final VideoListService service = (VideoListService) Context.getCurrent().getService();

      /**
   * 
   * getVideoList
   * 
   *
   * 
   * @return Response  
   * 
   */
  @GET
  @Path("/")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.TEXT_PLAIN)
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_INTERNAL_ERROR, message = "internalError"),
       @ApiResponse(code = HttpURLConnection.HTTP_OK, message = "videoListAsJSONArray"),
       @ApiResponse(code = HttpURLConnection.HTTP_NOT_FOUND, message = "noVideosExist")
  })
  @ApiOperation(value = "getVideoList", notes = " ")
  public Response getVideoList() {

    // internalError
    boolean internalError_condition = true;
    if(internalError_condition) {
      String er = "Some String";
      return Response.status(HttpURLConnection.HTTP_INTERNAL_ERROR).entity(er).build();
    }
    // videoListAsJSONArray
    boolean videoListAsJSONArray_condition = true;
    if(videoListAsJSONArray_condition) {
      JSONObject array = new JSONObject();
      return Response.status(HttpURLConnection.HTTP_OK).entity(array.toJSONString()).build();
    }
    // noVideosExist
    boolean noVideosExist_condition = true;
    if(noVideosExist_condition) {
      String er = "Some String";
      return Response.status(HttpURLConnection.HTTP_NOT_FOUND).entity(er).build();
    }
    return null;
  }



  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // Service methods (for inter service calls)
  // //////////////////////////////////////////////////////////////////////////////////////
  
  

}
