package i5.las2peer.services.echo;

import i5.las2peer.api.Context;
import i5.las2peer.api.ManualDeployment;
import i5.las2peer.restMapper.RESTService;
import i5.las2peer.restMapper.annotations.ServicePath;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import io.swagger.annotations.Contact;
import io.swagger.annotations.Info;
import io.swagger.annotations.License;
import io.swagger.annotations.SwaggerDefinition;
import org.json.simple.*;

import java.util.HashMap;
import java.util.Map;
 

/**
 *
 * echo-service2
 *
 * This microservice was generated by the CAE (Community Application Editor). If you edit it, please
 * make sure to keep the general structure of the file and only add the body of the methods provided
 * in this main file. Private methods are also allowed, but any "deeper" functionality should be
 * outsourced to (imported) classes.
 *
 */
@ServicePath("echo")
@ManualDeployment
public class echo extends RESTService {





  public echo() {
	super();
    // read and set properties values
    setFieldValues();
    
  }

  @Override
  public void initResources() {
	getResourceConfig().register(RootResource.class);
  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // REST methods
  // //////////////////////////////////////////////////////////////////////////////////////

  @Api
  @SwaggerDefinition(
      info = @Info(title = "echo-service2", version = "$Metadata_Version$",
          description = "$Metadata_Description$",
          termsOfService = "$Metadata_Terms$",
          contact = @Contact(name = "Philipp Hossner", email = "CAEAddress@gmail.com") ,
          license = @License(name = "BSD",
              url = "https://github.com/CAE-Community-Application-Editor/microservice-echo-service2/blob/master/LICENSE.txt") ) )
  @Path("/")
  public static class RootResource {

    private final echo service = (echo) Context.getCurrent().getService();

      /**
   * 
   * getEcho
   *
   * 
   * @param echoText  a String
   * 
   * @return Response 
   * 
   */
  @GET
  @Path("/echo")
  @Produces(MediaType.APPLICATION_JSON)
  @Consumes(MediaType.TEXT_PLAIN)
  @ApiResponses(value = {
       @ApiResponse(code = HttpURLConnection.HTTP_OK, message = "echoResponse")
  })
  @ApiOperation(value = "getEcho", notes = " ")
  public Response getEcho(String echoText) {

    JSONObject echoTextLogObj = new JSONObject();
    echoTextLogObj.put("payload", echoText);
    echoTextLogObj.put("payload_name", "echoText");
    echoTextLogObj.put("method", "GET");
    echoTextLogObj.put("resource", "echo");
    Context.get().monitorEvent((Object)null, MonitoringEvent.SERVICE_CUSTOM_MESSAGE_1, echoTextLogObj.toJSONString(), false);

    long processingStart = System.currentTimeMillis();

    // service method invocations


    long processingFinished = System.currentTimeMillis();
    long processingDuration = processingFinished - processingStart;
    JSONObject processingDurationObj = new JSONObject();
    processingDurationObj.put("time", processingDuration);
    processingDurationObj.put("method", "GET");
    processingDurationObj.put("resource", "echo");
    Context.get().monitorEvent((Object)null, MonitoringEvent.SERVICE_CUSTOM_MESSAGE_3, processingDurationObj.toJSONString(), false);

    // echoResponse
    boolean echoResponse_condition = true;
    if(echoResponse_condition) {
      JSONObject echoResult = new JSONObject();

      JSONObject responseLogObj = new JSONObject();
      responseLogObj.put("response", echoResult.toJSONString());
      responseLogObj.put("code", "200");
      responseLogObj.put("method", "GET");
      responseLogObj.put("resource", "echo");
      Context.get().monitorEvent((Object)null, MonitoringEvent.SERVICE_CUSTOM_MESSAGE_2, responseLogObj.toJSONString(), false);

      return Response.status(HttpURLConnection.HTTP_OK).entity(echoResult.toJSONString()).build();
    }
    return null;
  }



  }

  // //////////////////////////////////////////////////////////////////////////////////////
  // Service methods (for inter service calls)
  // //////////////////////////////////////////////////////////////////////////////////////
  
  

  // //////////////////////////////////////////////////////////////////////////////////////
  // Custom monitoring message descriptions (can be called via RMI)
  // //////////////////////////////////////////////////////////////////////////////////////

  public Map<String, String> getCustomMessageDescriptions() {
    Map<Integer, String> descriptions = new HashMap<>();
        descriptions.put("SERVICE_CUSTOM_MESSAGE_4", This is an additional custom message!);
    descriptions.put("SERVICE_CUSTOM_MESSAGE_2", "# HTTP Response of Method getEcho (GET)\n"
        + "\n"
        + "The response is logged according to the following JSON pattern:\n"
        + "```json\n"
        + "{ \"response\": <response_content>, \"code\": <http_code>, \"method\": <method_name>, \"resource\": <resource_name> }"
        + "```\n"
        + "## Example Measures\n"
        + "### getEcho Reponses\n"
        + "Show different responses that were returned to the users.\n"
        + "```sql\n"
        + "SELECT JSON_EXTRACT(REMARKS,\"$.response\") AS payload, COUNT(*) FROM MESSAGE WHERE EVENT=\"SERVICE_CUSTOM_MESSAGE_2\" AND SOURCE_AGENT = '$SERVICE$' GROUP BY JSON_EXTRACT(REMARKS,\"$.response\")\n"
        + "```\n"
        + "Visualization: bar chart or pie chart\n"
        + "\n"
        + "### Number of \"foo\" Responses in the last 24h\n"
        + "Count all responses where the content has been \"foo\" within the last 24 hours.\n"
        + "```sql\n"
        + "SELECT COUNT(*) FROM MESSAGE WHERE EVENT=\"SERVICE_CUSTOM_MESSAGE_2\" AND SOURCE_AGENT = '$SERVICE$' AND JSON_EXTRACT(REMARKS,\"$.response\") = \"foo\" AND TIME_STAMP >= DATE_SUB(NOW(), INTERVAL 1 DAY)\n"
        + "```\n"
        + "Visualization: value\n");
    descriptions.put("SERVICE_CUSTOM_MESSAGE_3", "# HTTP Response Duration of Method getEcho (GET)\n"
        + "\n"
        + "The number of milliseconds until the response is returned is logged according to the following JSON pattern:\n"
        + "```json\n"
        + "{ \"time\": <time_in_ms>, \"method\": <method_name>, \"resource\": <resource_name> }"
        + "```\n"
        + "## Example Measures\n"
        + "### Response Duration\n"
        + "Show in a line chart how long each request took to be processed.\n"
        + "```sql\n"
        + "SELECT TIME_STAMP, CAST(JSON_EXTRACT(REMARKS,\"$.time\") AS UNSIGNED) FROM MESSAGE WHERE EVENT=\"SERVICE_CUSTOM_MESSAGE_3\" AND SOURCE_AGENT = '$SERVICE$'\n"
        + "```\n"
        + "Visualization: line chart\n"
        + "\n"
        + "## Number of times getEcho (GET) took longer than 400ms\n"
        + "```sql\n"
        + "SELECT COUNT(*) FROM MESSAGE WHERE EVENT=\"SERVICE_CUSTOM_MESSAGE_3\" AND SOURCE_AGENT = '$SERVICE$' AND CAST(JSON_EXTRACT(REMARKS,\"$.time\") AS UNSIGNED) > 400\n"
        + "```\n"
        + "Visualization: line chart\n");
    descriptions.put("SERVICE_CUSTOM_MESSAGE_1", "# HTTP Payload of Method getEcho (GET)\n"
        + "\n"
        + "The payload *echoText* is logged according to the following JSON pattern:\n"
        + "```json\n"
        + "{ \"payload\": <payload_content>, \"payload_name\": <name_of_payload_variable>, \"method\": <method_name>, \"resource\": <resource_name> }"
        + "```\n"
        + "## Example Measures\n"
        + "### getEcho Payloads\n"
        + "Show different payloads that users have submitted.\n"
        + "```sql\n"
        + "SELECT JSON_EXTRACT(REMARKS,\"$.payload\") AS payload, COUNT(*) FROM MESSAGE WHERE EVENT=\"SERVICE_CUSTOM_MESSAGE_1\" AND SOURCE_AGENT = '$SERVICE$' GROUP BY JSON_EXTRACT(REMARKS,\"$.payload\")\n"
        + "```\n"
        + "Visualization: bar chart or pie chart\n"
        + "\n"
        + "### Number of \"foo\" Values in the last 24h\n"
        + "Count all requests where the payload has been \"foo\" within the last 24 hours."
        + "```sql\n"
        + "SELECT COUNT(*) FROM MESSAGE WHERE EVENT=\"SERVICE_CUSTOM_MESSAGE_1\" AND SOURCE_AGENT = '$SERVICE$' AND JSON_EXTRACT(REMARKS,\"$.payload\") = \"foo\" AND TIME_STAMP >= DATE_SUB(NOW(), INTERVAL 1 DAY)\n"
        + "```\n"
        + "Visualization: value\n");

    return descriptions;
  }

}
